// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hi/media/base.proto

package media

import (
	hi "github.com/HiWorld-56/hi-proto/go/hi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hi_media_base_proto protoreflect.FileDescriptor

const file_hi_media_base_proto_rawDesc = "" +
	"\n" +
	"\x13hi/media/base.proto\x12\bhi.media\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0fhi/common.proto\x1a\x10hi/options.proto2M\n" +
	"\x04Base\x12E\n" +
	"\rServerVersion\x12\x16.google.protobuf.Empty\x1a\x15.hi.ServerVersionResp\"\x05\x8a\xb5\x18\x01\x01B\x86\x01\n" +
	"\fcom.hi.mediaB\tBaseProtoP\x01Z*github.com/HiWorld-56/hi-proto/go/hi/media\xa2\x02\x03HMX\xaa\x02\bHi.Media\xca\x02\bHi\\Media\xe2\x02\x14Hi\\Media\\GPBMetadata\xea\x02\tHi::Mediab\x06proto3"

var file_hi_media_base_proto_goTypes = []any{
	(*emptypb.Empty)(nil),        // 0: google.protobuf.Empty
	(*hi.ServerVersionResp)(nil), // 1: hi.ServerVersionResp
}
var file_hi_media_base_proto_depIdxs = []int32{
	0, // 0: hi.media.Base.ServerVersion:input_type -> google.protobuf.Empty
	1, // 1: hi.media.Base.ServerVersion:output_type -> hi.ServerVersionResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hi_media_base_proto_init() }
func file_hi_media_base_proto_init() {
	if File_hi_media_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hi_media_base_proto_rawDesc), len(file_hi_media_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hi_media_base_proto_goTypes,
		DependencyIndexes: file_hi_media_base_proto_depIdxs,
	}.Build()
	File_hi_media_base_proto = out.File
	file_hi_media_base_proto_goTypes = nil
	file_hi_media_base_proto_depIdxs = nil
}
