# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hi/club/trade/base.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hi/club/trade/base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hi.club import order_pb2 as hi_dot_club_dot_order__pb2
from hi.club import trade_pb2 as hi_dot_club_dot_trade__pb2
from hi import common_pb2 as hi_dot_common__pb2
from hi import options_pb2 as hi_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18hi/club/trade/base.proto\x12\rhi.club.trade\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13hi/club/order.proto\x1a\x13hi/club/trade.proto\x1a\x0fhi/common.proto\x1a\x10hi/options.proto\"a\n\rListTradesReq\x12\x10\n\x03\x64id\x18\x01 \x01(\tR\x03\x64id\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\x12.\n\npagination\x18\x03 \x01(\x0b\x32\x0e.hi.PaginationR\npagination2\xd6\x02\n\x05Trade\x12\x42\n\x06GetFee\x12\x17.hi.club.GetTradeFeeReq\x1a\x18.hi.club.GetTradeFeeResp\"\x05\x8a\xb5\x18\x01\x06\x12\x39\n\x03Get\x12\x14.hi.club.GetTradeReq\x1a\x15.hi.club.GetTradeResp\"\x05\x8a\xb5\x18\x01\x06\x12\x39\n\x03\x41\x64\x64\x12\x14.hi.club.AddTradeReq\x1a\x15.hi.club.AddTradeResp\"\x05\x8a\xb5\x18\x01\x06\x12M\n\x0fUpdateTransHash\x12\x1b.hi.club.UpdateTransHashReq\x1a\x16.google.protobuf.Empty\"\x05\x8a\xb5\x18\x01\x06\x12\x44\n\x04List\x12\x1c.hi.club.trade.ListTradesReq\x1a\x17.hi.club.ListTradesResp\"\x05\x8a\xb5\x18\x01\x06\x32R\n\x0bTradeManage\x12\x43\n\x04List\x12\x1b.hi.club.TradeManageListReq\x1a\x17.hi.club.ListTradesResp\"\x05\x8a\xb5\x18\x01\x06\x32x\n\x05Order\x12\x36\n\x04Pull\x12\x0e.hi.SignedData\x1a\x17.hi.club.PullOrdersResp\"\x05\x8a\xb5\x18\x01\x06\x12\x37\n\x06Report\x12\x0e.hi.SignedData\x1a\x16.google.protobuf.Empty\"\x05\x8a\xb5\x18\x01\x06\x42\x31Z/github.com/HiWorld-56/hi-proto/go/hi/club/tradeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hi.club.trade.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/HiWorld-56/hi-proto/go/hi/club/trade'
  _globals['_TRADE'].methods_by_name['GetFee']._loaded_options = None
  _globals['_TRADE'].methods_by_name['GetFee']._serialized_options = b'\212\265\030\001\006'
  _globals['_TRADE'].methods_by_name['Get']._loaded_options = None
  _globals['_TRADE'].methods_by_name['Get']._serialized_options = b'\212\265\030\001\006'
  _globals['_TRADE'].methods_by_name['Add']._loaded_options = None
  _globals['_TRADE'].methods_by_name['Add']._serialized_options = b'\212\265\030\001\006'
  _globals['_TRADE'].methods_by_name['UpdateTransHash']._loaded_options = None
  _globals['_TRADE'].methods_by_name['UpdateTransHash']._serialized_options = b'\212\265\030\001\006'
  _globals['_TRADE'].methods_by_name['List']._loaded_options = None
  _globals['_TRADE'].methods_by_name['List']._serialized_options = b'\212\265\030\001\006'
  _globals['_TRADEMANAGE'].methods_by_name['List']._loaded_options = None
  _globals['_TRADEMANAGE'].methods_by_name['List']._serialized_options = b'\212\265\030\001\006'
  _globals['_ORDER'].methods_by_name['Pull']._loaded_options = None
  _globals['_ORDER'].methods_by_name['Pull']._serialized_options = b'\212\265\030\001\006'
  _globals['_ORDER'].methods_by_name['Report']._loaded_options = None
  _globals['_ORDER'].methods_by_name['Report']._serialized_options = b'\212\265\030\001\006'
  _globals['_LISTTRADESREQ']._serialized_start=149
  _globals['_LISTTRADESREQ']._serialized_end=246
  _globals['_TRADE']._serialized_start=249
  _globals['_TRADE']._serialized_end=591
  _globals['_TRADEMANAGE']._serialized_start=593
  _globals['_TRADEMANAGE']._serialized_end=675
  _globals['_ORDER']._serialized_start=677
  _globals['_ORDER']._serialized_end=797
# @@protoc_insertion_point(module_scope)
