# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hi/media/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hi/media/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hi import common_pb2 as hi_dot_common__pb2
from hi.did import auth_pb2 as hi_dot_did_dot_auth__pb2
from hi import options_pb2 as hi_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hi/media/auth.proto\x12\x08hi.media\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0fhi/common.proto\x1a\x11hi/did/auth.proto\x1a\x10hi/options.proto2\x85\x02\n\x04\x41uth\x12?\n\rGenerateReqId\x12\x18.hi.did.GenerateReqIdReq\x1a\r.hi.RequestId\"\x05\x8a\xb5\x18\x01\x01\x12;\n\x0cGetReqStatus\x12\r.hi.RequestId\x1a\x15.hi.did.ReqStatusResp\"\x05\x8a\xb5\x18\x01\x01\x12=\n\x0cRefreshToken\x12\x17.hi.did.RefreshTokenReq\x1a\r.hi.AuthToken\"\x05\x8a\xb5\x18\x01\x01\x12@\n\x06Logout\x12\x17.hi.did.RefreshTokenReq\x1a\x16.google.protobuf.Empty\"\x05\x8a\xb5\x18\x01\x01\x42,Z*github.com/HiWorld-56/hi-proto/go/hi/mediab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hi.media.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/HiWorld-56/hi-proto/go/hi/media'
  _globals['_AUTH'].methods_by_name['GenerateReqId']._loaded_options = None
  _globals['_AUTH'].methods_by_name['GenerateReqId']._serialized_options = b'\212\265\030\001\001'
  _globals['_AUTH'].methods_by_name['GetReqStatus']._loaded_options = None
  _globals['_AUTH'].methods_by_name['GetReqStatus']._serialized_options = b'\212\265\030\001\001'
  _globals['_AUTH'].methods_by_name['RefreshToken']._loaded_options = None
  _globals['_AUTH'].methods_by_name['RefreshToken']._serialized_options = b'\212\265\030\001\001'
  _globals['_AUTH'].methods_by_name['Logout']._loaded_options = None
  _globals['_AUTH'].methods_by_name['Logout']._serialized_options = b'\212\265\030\001\001'
  _globals['_AUTH']._serialized_start=117
  _globals['_AUTH']._serialized_end=378
# @@protoc_insertion_point(module_scope)
