// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hi/did/source.proto

package did

import (
	context "context"
	hi "github.com/HiWorld-56/hi-proto/go/hi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Source_UploadAvatar_FullMethodName = "/hi.did.Source/UploadAvatar"
)

// SourceClient is the client API for Source service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Source —— hidid 侧直接搬运二进制的方法。分法见 hi/club/source.proto 的说明。
//
// **所有身份实体的头像都落 hidid/avatar/**:用户、商户(logo 即商户头像)、机器人,
// 不再按实体分目录 —— 它们在存储上是同一类东西,分开只是徒增分支。
// 以前不分家(全塞 upload 的按月目录)出过批量误删头像的事故,那是"不该合的合了";
// 这里是"不该分的分了",两回事。
//
// ⚠️ 只回 url,**不改资料** —— 落库分别走 `User.Edit` / `Merchant.Update` /
//
//	`Merchant.SetUsers`,上传与落库解耦(这个约定原先就是这样,只是方法搬了家)。
type SourceClient interface {
	UploadAvatar(ctx context.Context, in *hi.UploadReq, opts ...grpc.CallOption) (*hi.UploadResp, error)
}

type sourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceClient(cc grpc.ClientConnInterface) SourceClient {
	return &sourceClient{cc}
}

func (c *sourceClient) UploadAvatar(ctx context.Context, in *hi.UploadReq, opts ...grpc.CallOption) (*hi.UploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hi.UploadResp)
	err := c.cc.Invoke(ctx, Source_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServer is the server API for Source service.
// All implementations should embed UnimplementedSourceServer
// for forward compatibility.
//
// Source —— hidid 侧直接搬运二进制的方法。分法见 hi/club/source.proto 的说明。
//
// **所有身份实体的头像都落 hidid/avatar/**:用户、商户(logo 即商户头像)、机器人,
// 不再按实体分目录 —— 它们在存储上是同一类东西,分开只是徒增分支。
// 以前不分家(全塞 upload 的按月目录)出过批量误删头像的事故,那是"不该合的合了";
// 这里是"不该分的分了",两回事。
//
// ⚠️ 只回 url,**不改资料** —— 落库分别走 `User.Edit` / `Merchant.Update` /
//
//	`Merchant.SetUsers`,上传与落库解耦(这个约定原先就是这样,只是方法搬了家)。
type SourceServer interface {
	UploadAvatar(context.Context, *hi.UploadReq) (*hi.UploadResp, error)
}

// UnimplementedSourceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServer struct{}

func (UnimplementedSourceServer) UploadAvatar(context.Context, *hi.UploadReq) (*hi.UploadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedSourceServer) testEmbeddedByValue() {}

// UnsafeSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServer will
// result in compilation errors.
type UnsafeSourceServer interface {
	mustEmbedUnimplementedSourceServer()
}

func RegisterSourceServer(s grpc.ServiceRegistrar, srv SourceServer) {
	// If the following call panics, it indicates UnimplementedSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Source_ServiceDesc, srv)
}

func _Source_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hi.UploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).UploadAvatar(ctx, req.(*hi.UploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Source_ServiceDesc is the grpc.ServiceDesc for Source service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Source_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hi.did.Source",
	HandlerType: (*SourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAvatar",
			Handler:    _Source_UploadAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hi/did/source.proto",
}

const (
	MerchantSource_UploadAvatar_FullMethodName = "/hi.did.MerchantSource/UploadAvatar"
)

// MerchantSourceClient is the client API for MerchantSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MerchantSource —— 同样是传头像,但**调用主体是商户**(商户给名下用户传)。
//
// 拆成独立 service 而不是在 Source 里加一个方法:`hi.auth` 要求同一 service 内档位
// 一致,商户档与用户档不能混。这也正是 Merchant / MerchantGranted 的拆法。
type MerchantSourceClient interface {
	UploadAvatar(ctx context.Context, in *hi.UploadReq, opts ...grpc.CallOption) (*hi.UploadResp, error)
}

type merchantSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantSourceClient(cc grpc.ClientConnInterface) MerchantSourceClient {
	return &merchantSourceClient{cc}
}

func (c *merchantSourceClient) UploadAvatar(ctx context.Context, in *hi.UploadReq, opts ...grpc.CallOption) (*hi.UploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hi.UploadResp)
	err := c.cc.Invoke(ctx, MerchantSource_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantSourceServer is the server API for MerchantSource service.
// All implementations should embed UnimplementedMerchantSourceServer
// for forward compatibility.
//
// MerchantSource —— 同样是传头像,但**调用主体是商户**(商户给名下用户传)。
//
// 拆成独立 service 而不是在 Source 里加一个方法:`hi.auth` 要求同一 service 内档位
// 一致,商户档与用户档不能混。这也正是 Merchant / MerchantGranted 的拆法。
type MerchantSourceServer interface {
	UploadAvatar(context.Context, *hi.UploadReq) (*hi.UploadResp, error)
}

// UnimplementedMerchantSourceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantSourceServer struct{}

func (UnimplementedMerchantSourceServer) UploadAvatar(context.Context, *hi.UploadReq) (*hi.UploadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedMerchantSourceServer) testEmbeddedByValue() {}

// UnsafeMerchantSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantSourceServer will
// result in compilation errors.
type UnsafeMerchantSourceServer interface {
	mustEmbedUnimplementedMerchantSourceServer()
}

func RegisterMerchantSourceServer(s grpc.ServiceRegistrar, srv MerchantSourceServer) {
	// If the following call panics, it indicates UnimplementedMerchantSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantSource_ServiceDesc, srv)
}

func _MerchantSource_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hi.UploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantSourceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantSource_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantSourceServer).UploadAvatar(ctx, req.(*hi.UploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantSource_ServiceDesc is the grpc.ServiceDesc for MerchantSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hi.did.MerchantSource",
	HandlerType: (*MerchantSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAvatar",
			Handler:    _MerchantSource_UploadAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hi/did/source.proto",
}
