// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hi/ninja/ipc.proto

package ninja

import (
	hi "github.com/HiWorld-56/hi-proto/go/hi"
	ai "github.com/HiWorld-56/hi-proto/go/hi/ai"
	club "github.com/HiWorld-56/hi-proto/go/hi/club"
	did "github.com/HiWorld-56/hi-proto/go/hi/did"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 二态开关：语音监听开始/结束、音频播放开始/结束等
type StateToggle int32

const (
	StateToggle_STATE_UNKNOWN StateToggle = 0
	StateToggle_STATE_START   StateToggle = 1
	StateToggle_STATE_END     StateToggle = 2
)

// Enum value maps for StateToggle.
var (
	StateToggle_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_START",
		2: "STATE_END",
	}
	StateToggle_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_START":   1,
		"STATE_END":     2,
	}
)

func (x StateToggle) Enum() *StateToggle {
	p := new(StateToggle)
	*p = x
	return p
}

func (x StateToggle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateToggle) Descriptor() protoreflect.EnumDescriptor {
	return file_hi_ninja_ipc_proto_enumTypes[0].Descriptor()
}

func (StateToggle) Type() protoreflect.EnumType {
	return &file_hi_ninja_ipc_proto_enumTypes[0]
}

func (x StateToggle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateToggle.Descriptor instead.
func (StateToggle) EnumDescriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{0}
}

// 机器人情绪表达
type Emotion int32

const (
	Emotion_EMOTION_UNKNOWN   Emotion = 0
	Emotion_EMOTION_ANGER     Emotion = 1
	Emotion_EMOTION_LAUGH     Emotion = 2
	Emotion_EMOTION_FRUSTRATE Emotion = 3
)

// Enum value maps for Emotion.
var (
	Emotion_name = map[int32]string{
		0: "EMOTION_UNKNOWN",
		1: "EMOTION_ANGER",
		2: "EMOTION_LAUGH",
		3: "EMOTION_FRUSTRATE",
	}
	Emotion_value = map[string]int32{
		"EMOTION_UNKNOWN":   0,
		"EMOTION_ANGER":     1,
		"EMOTION_LAUGH":     2,
		"EMOTION_FRUSTRATE": 3,
	}
)

func (x Emotion) Enum() *Emotion {
	p := new(Emotion)
	*p = x
	return p
}

func (x Emotion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Emotion) Descriptor() protoreflect.EnumDescriptor {
	return file_hi_ninja_ipc_proto_enumTypes[1].Descriptor()
}

func (Emotion) Type() protoreflect.EnumType {
	return &file_hi_ninja_ipc_proto_enumTypes[1]
}

func (x Emotion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Emotion.Descriptor instead.
func (Emotion) EnumDescriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{1}
}

type PluginProgress_State int32

const (
	PluginProgress_STATE_UNKNOWN     PluginProgress_State = 0
	PluginProgress_STATE_DOWNLOADING PluginProgress_State = 1 // 正在下载
	PluginProgress_STATE_INSTALLING  PluginProgress_State = 2 // 已下完,正在落盘/加载
	PluginProgress_STATE_DONE        PluginProgress_State = 3 // 装好了(已热加载,可以用了)
	PluginProgress_STATE_FAILED      PluginProgress_State = 4 // 这一个失败了 —— **不影响其它插件**
)

// Enum value maps for PluginProgress_State.
var (
	PluginProgress_State_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_DOWNLOADING",
		2: "STATE_INSTALLING",
		3: "STATE_DONE",
		4: "STATE_FAILED",
	}
	PluginProgress_State_value = map[string]int32{
		"STATE_UNKNOWN":     0,
		"STATE_DOWNLOADING": 1,
		"STATE_INSTALLING":  2,
		"STATE_DONE":        3,
		"STATE_FAILED":      4,
	}
)

func (x PluginProgress_State) Enum() *PluginProgress_State {
	p := new(PluginProgress_State)
	*p = x
	return p
}

func (x PluginProgress_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginProgress_State) Descriptor() protoreflect.EnumDescriptor {
	return file_hi_ninja_ipc_proto_enumTypes[2].Descriptor()
}

func (PluginProgress_State) Type() protoreflect.EnumType {
	return &file_hi_ninja_ipc_proto_enumTypes[2]
}

func (x PluginProgress_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginProgress_State.Descriptor instead.
func (PluginProgress_State) EnumDescriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{12, 0}
}

type UpdateAction_Action int32

const (
	UpdateAction_ACTION_UNKNOWN UpdateAction_Action = 0
	UpdateAction_ACTION_CHECK   UpdateAction_Action = 1
	UpdateAction_ACTION_APPLY   UpdateAction_Action = 2
	UpdateAction_ACTION_DISMISS UpdateAction_Action = 3
)

// Enum value maps for UpdateAction_Action.
var (
	UpdateAction_Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_CHECK",
		2: "ACTION_APPLY",
		3: "ACTION_DISMISS",
	}
	UpdateAction_Action_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"ACTION_CHECK":   1,
		"ACTION_APPLY":   2,
		"ACTION_DISMISS": 3,
	}
)

func (x UpdateAction_Action) Enum() *UpdateAction_Action {
	p := new(UpdateAction_Action)
	*p = x
	return p
}

func (x UpdateAction_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateAction_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_hi_ninja_ipc_proto_enumTypes[3].Descriptor()
}

func (UpdateAction_Action) Type() protoreflect.EnumType {
	return &file_hi_ninja_ipc_proto_enumTypes[3]
}

func (x UpdateAction_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateAction_Action.Descriptor instead.
func (UpdateAction_Action) EnumDescriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{13, 0}
}

// 机器人初始化：自身身份 + 当前所有者
// master 缺省表示尚未绑定所有者
type RobotInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robot         *hi.Entity             `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	Master        *hi.Entity             `protobuf:"bytes,2,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotInit) Reset() {
	*x = RobotInit{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInit) ProtoMessage() {}

func (x *RobotInit) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInit.ProtoReflect.Descriptor instead.
func (*RobotInit) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *RobotInit) GetRobot() *hi.Entity {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *RobotInit) GetMaster() *hi.Entity {
	if x != nil {
		return x.Master
	}
	return nil
}

// 好友列表（全量，初始化时推送）
type FriendList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*hi.Entity           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendList) Reset() {
	*x = FriendList{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendList) ProtoMessage() {}

func (x *FriendList) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendList.ProtoReflect.Descriptor instead.
func (*FriendList) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *FriendList) GetList() []*hi.Entity {
	if x != nil {
		return x.List
	}
	return nil
}

// 群成员列表（全量，初始化时批量推送）
type GroupInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*club.GroupInfo      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoList) Reset() {
	*x = GroupInfoList{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoList) ProtoMessage() {}

func (x *GroupInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoList.ProtoReflect.Descriptor instead.
func (*GroupInfoList) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfoList) GetList() []*club.GroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 所有者变更事件
// trigger: bind（新绑定）/ unbind（解绑，此时 master 缺省）/ update（资料更新，绑定关系不变）
type MasterEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Master *hi.Entity             `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	// 触发源:
	//
	//	bind    绑定了主人(master = 新主人)
	//	unbind  解绑(master 不传)
	//	update  **主人还是那个人,但他改了资料**(master = 主人当前完整的 Entity)
	//
	// ⚠️ update 这档别按 did 判重 —— did 没变正是它的常态,变的是 name/avatar。
	Trigger       *string `protobuf:"bytes,2,opt,name=trigger,proto3,oneof" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterEvent) Reset() {
	*x = MasterEvent{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterEvent) ProtoMessage() {}

func (x *MasterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterEvent.ProtoReflect.Descriptor instead.
func (*MasterEvent) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *MasterEvent) GetMaster() *hi.Entity {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *MasterEvent) GetTrigger() string {
	if x != nil && x.Trigger != nil {
		return *x.Trigger
	}
	return ""
}

// AI 文字回复
// uuid 由 brain 在本次对话开始时生成，通过 show_im_request（覆写 Message.uuid）
// 和 show_im_reply / show_voice_reply 两端传递，face 据此将回复路由到对应的对话框。
// value 为 AI 输出的纯文本，不封装为 Message 结构。
type TextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextReply) Reset() {
	*x = TextReply{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReply) ProtoMessage() {}

func (x *TextReply) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReply.ProtoReflect.Descriptor instead.
func (*TextReply) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *TextReply) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *TextReply) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// TTS 音频播放
// uuid 与对应的 TextReply.uuid 一致，audio 为完整音频文件的原始字节。
type AudioPlay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Audio         []byte                 `protobuf:"bytes,2,opt,name=audio,proto3,oneof" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPlay) Reset() {
	*x = AudioPlay{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPlay) ProtoMessage() {}

func (x *AudioPlay) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPlay.ProtoReflect.Descriptor instead.
func (*AudioPlay) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *AudioPlay) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *AudioPlay) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

// 币安接入设置。**凭证与业务参数分开放** —— 初始本金不是凭证，
// 它是算累计收益用的基数；混在一条里，改一次本金就得把 api_secret 整条重发一遍。
type BinanceSettings struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Credentials *BinanceCredentials    `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// 初始本金。**十进制字符串**，与本仓所有金额字段同口径（免浮点误差）。
	InitialCapital *string `protobuf:"bytes,2,opt,name=initial_capital,json=initialCapital,proto3,oneof" json:"initial_capital,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BinanceSettings) Reset() {
	*x = BinanceSettings{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinanceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinanceSettings) ProtoMessage() {}

func (x *BinanceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinanceSettings.ProtoReflect.Descriptor instead.
func (*BinanceSettings) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *BinanceSettings) GetCredentials() *BinanceCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *BinanceSettings) GetInitialCapital() string {
	if x != nil && x.InitialCapital != nil {
		return *x.InitialCapital
	}
	return ""
}

// 币安 API 凭证。
// ⚠️ `api_secret` 是敏感字段，**只允许走 brain ↔ face 这条本地 ZMQ**，不出机器。
type BinanceCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *string                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`
	ApiSecret     *string                `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3,oneof" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinanceCredentials) Reset() {
	*x = BinanceCredentials{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinanceCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinanceCredentials) ProtoMessage() {}

func (x *BinanceCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinanceCredentials.ProtoReflect.Descriptor instead.
func (*BinanceCredentials) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *BinanceCredentials) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *BinanceCredentials) GetApiSecret() string {
	if x != nil && x.ApiSecret != nil {
		return *x.ApiSecret
	}
	return ""
}

// brain -> face：所有指令通过 oneof 路由
type BrainToFace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*BrainToFace_InitRobot
	//	*BrainToFace_ShowListen
	//	*BrainToFace_ShowEmotion
	//	*BrainToFace_ShowImRequest
	//	*BrainToFace_ShowImReply
	//	*BrainToFace_ShowVoiceReply
	//	*BrainToFace_ShowQrCode
	//	*BrainToFace_EventRobot
	//	*BrainToFace_EventMaster
	//	*BrainToFace_EventMembers
	//	*BrainToFace_EventPlugin
	//	*BrainToFace_EventPluginProgress
	//	*BrainToFace_EventTransaction
	//	*BrainToFace_PlayAudio
	//	*BrainToFace_EventFriends
	//	*BrainToFace_EventFriendDelete
	//	*BrainToFace_EventFriendAdd
	//	*BrainToFace_MembersInit
	//	*BrainToFace_EventStatus
	//	*BrainToFace_EventUpdate
	//	*BrainToFace_EventBinanceSettings
	Cmd           isBrainToFace_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrainToFace) Reset() {
	*x = BrainToFace{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrainToFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrainToFace) ProtoMessage() {}

func (x *BrainToFace) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrainToFace.ProtoReflect.Descriptor instead.
func (*BrainToFace) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *BrainToFace) GetCmd() isBrainToFace_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *BrainToFace) GetInitRobot() *RobotInit {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_InitRobot); ok {
			return x.InitRobot
		}
	}
	return nil
}

func (x *BrainToFace) GetShowListen() StateToggle {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowListen); ok {
			return x.ShowListen
		}
	}
	return StateToggle_STATE_UNKNOWN
}

func (x *BrainToFace) GetShowEmotion() Emotion {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowEmotion); ok {
			return x.ShowEmotion
		}
	}
	return Emotion_EMOTION_UNKNOWN
}

func (x *BrainToFace) GetShowImRequest() *club.Message {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowImRequest); ok {
			return x.ShowImRequest
		}
	}
	return nil
}

func (x *BrainToFace) GetShowImReply() *TextReply {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowImReply); ok {
			return x.ShowImReply
		}
	}
	return nil
}

func (x *BrainToFace) GetShowVoiceReply() *TextReply {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowVoiceReply); ok {
			return x.ShowVoiceReply
		}
	}
	return nil
}

func (x *BrainToFace) GetShowQrCode() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_ShowQrCode); ok {
			return x.ShowQrCode
		}
	}
	return nil
}

func (x *BrainToFace) GetEventRobot() *hi.Entity {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventRobot); ok {
			return x.EventRobot
		}
	}
	return nil
}

func (x *BrainToFace) GetEventMaster() *MasterEvent {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventMaster); ok {
			return x.EventMaster
		}
	}
	return nil
}

func (x *BrainToFace) GetEventMembers() *club.GroupInfo {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventMembers); ok {
			return x.EventMembers
		}
	}
	return nil
}

func (x *BrainToFace) GetEventPlugin() *ai.PluginView {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventPlugin); ok {
			return x.EventPlugin
		}
	}
	return nil
}

func (x *BrainToFace) GetEventPluginProgress() *PluginProgress {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventPluginProgress); ok {
			return x.EventPluginProgress
		}
	}
	return nil
}

func (x *BrainToFace) GetEventTransaction() *did.Transaction {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventTransaction); ok {
			return x.EventTransaction
		}
	}
	return nil
}

func (x *BrainToFace) GetPlayAudio() *AudioPlay {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_PlayAudio); ok {
			return x.PlayAudio
		}
	}
	return nil
}

func (x *BrainToFace) GetEventFriends() *FriendList {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventFriends); ok {
			return x.EventFriends
		}
	}
	return nil
}

func (x *BrainToFace) GetEventFriendDelete() *hi.Entity {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventFriendDelete); ok {
			return x.EventFriendDelete
		}
	}
	return nil
}

func (x *BrainToFace) GetEventFriendAdd() *hi.Entity {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventFriendAdd); ok {
			return x.EventFriendAdd
		}
	}
	return nil
}

func (x *BrainToFace) GetMembersInit() *GroupInfoList {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_MembersInit); ok {
			return x.MembersInit
		}
	}
	return nil
}

func (x *BrainToFace) GetEventStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventStatus); ok {
			return x.EventStatus
		}
	}
	return nil
}

func (x *BrainToFace) GetEventUpdate() *UpdateInfo {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventUpdate); ok {
			return x.EventUpdate
		}
	}
	return nil
}

func (x *BrainToFace) GetEventBinanceSettings() *BinanceSettings {
	if x != nil {
		if x, ok := x.Cmd.(*BrainToFace_EventBinanceSettings); ok {
			return x.EventBinanceSettings
		}
	}
	return nil
}

type isBrainToFace_Cmd interface {
	isBrainToFace_Cmd()
}

type BrainToFace_InitRobot struct {
	// 初始化
	InitRobot *RobotInit `protobuf:"bytes,1,opt,name=init_robot,json=initRobot,proto3,oneof"` // face 上线时推送，携带机器人和所有者身份
}

type BrainToFace_ShowListen struct {
	// 交互状态
	ShowListen StateToggle `protobuf:"varint,2,opt,name=show_listen,json=showListen,proto3,enum=hi.ninja.StateToggle,oneof"` // 语音监听开始/结束
}

type BrainToFace_ShowEmotion struct {
	ShowEmotion Emotion `protobuf:"varint,3,opt,name=show_emotion,json=showEmotion,proto3,enum=hi.ninja.Emotion,oneof"` // 情绪表达
}

type BrainToFace_ShowImRequest struct {
	// 对话内容
	ShowImRequest *club.Message `protobuf:"bytes,4,opt,name=show_im_request,json=showImRequest,proto3,oneof"` // 收到 IM 消息（单聊/所有者/群聊）
}

type BrainToFace_ShowImReply struct {
	ShowImReply *TextReply `protobuf:"bytes,5,opt,name=show_im_reply,json=showImReply,proto3,oneof"` // IM 对话的 AI 回复
}

type BrainToFace_ShowVoiceReply struct {
	ShowVoiceReply *TextReply `protobuf:"bytes,6,opt,name=show_voice_reply,json=showVoiceReply,proto3,oneof"` // 语音对话的 AI 回复
}

type BrainToFace_ShowQrCode struct {
	ShowQrCode *emptypb.Empty `protobuf:"bytes,7,opt,name=show_qr_code,json=showQrCode,proto3,oneof"` // 展示机器人 DID 二维码
}

type BrainToFace_EventRobot struct {
	// 状态事件
	EventRobot *hi.Entity `protobuf:"bytes,8,opt,name=event_robot,json=eventRobot,proto3,oneof"` // 机器人自身资料变更
}

type BrainToFace_EventMaster struct {
	EventMaster *MasterEvent `protobuf:"bytes,9,opt,name=event_master,json=eventMaster,proto3,oneof"` // 所有者绑定状态变化
}

type BrainToFace_EventMembers struct {
	EventMembers *club.GroupInfo `protobuf:"bytes,10,opt,name=event_members,json=eventMembers,proto3,oneof"` // 群成员列表（全量）
}

type BrainToFace_EventPlugin struct {
	EventPlugin *ai.PluginView `protobuf:"bytes,11,opt,name=event_plugin,json=eventPlugin,proto3,oneof"` // 插件加载完成
}

type BrainToFace_EventPluginProgress struct {
	EventPluginProgress *PluginProgress `protobuf:"bytes,20,opt,name=event_plugin_progress,json=eventPluginProgress,proto3,oneof"` // 插件下载/安装进度
}

type BrainToFace_EventTransaction struct {
	EventTransaction *did.Transaction `protobuf:"bytes,12,opt,name=event_transaction,json=eventTransaction,proto3,oneof"` // 收到转账
}

type BrainToFace_PlayAudio struct {
	// 媒体：uuid="" 时路由到 dialog_voice，否则按 uuid 路由到对应 IM dialog
	PlayAudio *AudioPlay `protobuf:"bytes,13,opt,name=play_audio,json=playAudio,proto3,oneof"` // TTS 音频播放
}

type BrainToFace_EventFriends struct {
	// 好友变更
	EventFriends *FriendList `protobuf:"bytes,15,opt,name=event_friends,json=eventFriends,proto3,oneof"` // 好友列表全量推送（初始化时）
}

type BrainToFace_EventFriendDelete struct {
	EventFriendDelete *hi.Entity `protobuf:"bytes,14,opt,name=event_friend_delete,json=eventFriendDelete,proto3,oneof"` // 被对方删除好友，face 从单聊列表移除该成员
}

type BrainToFace_EventFriendAdd struct {
	EventFriendAdd *hi.Entity `protobuf:"bytes,16,opt,name=event_friend_add,json=eventFriendAdd,proto3,oneof"` // 新增好友，face 将其加入单聊成员列表
}

type BrainToFace_MembersInit struct {
	// 群成员初始化（全量批量，初始化时推送）
	MembersInit *GroupInfoList `protobuf:"bytes,17,opt,name=members_init,json=membersInit,proto3,oneof"`
}

type BrainToFace_EventStatus struct {
	// 系统状态：NTP 时间同步 + 网络连通性（face 上线推送 + 状态变化时推送）
	EventStatus *StatusEvent `protobuf:"bytes,18,opt,name=event_status,json=eventStatus,proto3,oneof"`
}

type BrainToFace_EventUpdate struct {
	// 资源更新信息同步
	EventUpdate *UpdateInfo `protobuf:"bytes,19,opt,name=event_update,json=eventUpdate,proto3,oneof"`
}

type BrainToFace_EventBinanceSettings struct {
	// 币安设置同步（凭证 + 初始本金；仅限本地 face IPC）
	EventBinanceSettings *BinanceSettings `protobuf:"bytes,21,opt,name=event_binance_settings,json=eventBinanceSettings,proto3,oneof"`
}

func (*BrainToFace_InitRobot) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowListen) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowEmotion) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowImRequest) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowImReply) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowVoiceReply) isBrainToFace_Cmd() {}

func (*BrainToFace_ShowQrCode) isBrainToFace_Cmd() {}

func (*BrainToFace_EventRobot) isBrainToFace_Cmd() {}

func (*BrainToFace_EventMaster) isBrainToFace_Cmd() {}

func (*BrainToFace_EventMembers) isBrainToFace_Cmd() {}

func (*BrainToFace_EventPlugin) isBrainToFace_Cmd() {}

func (*BrainToFace_EventPluginProgress) isBrainToFace_Cmd() {}

func (*BrainToFace_EventTransaction) isBrainToFace_Cmd() {}

func (*BrainToFace_PlayAudio) isBrainToFace_Cmd() {}

func (*BrainToFace_EventFriends) isBrainToFace_Cmd() {}

func (*BrainToFace_EventFriendDelete) isBrainToFace_Cmd() {}

func (*BrainToFace_EventFriendAdd) isBrainToFace_Cmd() {}

func (*BrainToFace_MembersInit) isBrainToFace_Cmd() {}

func (*BrainToFace_EventStatus) isBrainToFace_Cmd() {}

func (*BrainToFace_EventUpdate) isBrainToFace_Cmd() {}

func (*BrainToFace_EventBinanceSettings) isBrainToFace_Cmd() {}

// 系统状态快照
// ntp:  系统时间已同步（时间戳 > 1_750_000_000，即 2025-06 之后）
// wifi: 服务器 TCP 443 可达
type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ntp           *bool                  `protobuf:"varint,1,opt,name=ntp,proto3,oneof" json:"ntp,omitempty"`
	Wifi          *bool                  `protobuf:"varint,2,opt,name=wifi,proto3,oneof" json:"wifi,omitempty"`
	Usb           *bool                  `protobuf:"varint,3,opt,name=usb,proto3,oneof" json:"usb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *StatusEvent) GetNtp() bool {
	if x != nil && x.Ntp != nil {
		return *x.Ntp
	}
	return false
}

func (x *StatusEvent) GetWifi() bool {
	if x != nil && x.Wifi != nil {
		return *x.Wifi
	}
	return false
}

func (x *StatusEvent) GetUsb() bool {
	if x != nil && x.Usb != nil {
		return *x.Usb
	}
	return false
}

// 资源更新进度信息
// `state`：当前更新状态，例如 `idle`、`checking`、`downloading`、`installing`、`success`、`failed` 等。
// `current_version`：当前已安装/正在运行的版本号。
// `target_version`：目标版本号，也就是准备更新到的版本。
// `progress`： 更新进度，通常是 `0-100` 的百分比。
// `message` ： 给用户或前端展示的状态说明，例如“正在下载更新包”。
// `error` ：错误信息。更新失败时记录失败原因；正常情况下不传。
// `changes` ：版本变更列表，通常是 changelog，例如修复了哪些问题、增加了哪些功能。
// `trigger`：更新触发来源，例如 `manual` 手动触发、`auto` 自动检查、`startup` 启动时触发等。
// `updated_at` ：状态最后更新时间，通常是 Unix 时间戳。具体是秒还是毫秒要看实现约定。
// `downloaded_bytes`：已下载的字节数。
// `total_bytes`：需要下载的总字节数。可用于计算下载百分比。
type UpdateInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           *string                `protobuf:"bytes,1,opt,name=state,proto3,oneof" json:"state,omitempty"`
	CurrentVersion  *string                `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3,oneof" json:"current_version,omitempty"`
	TargetVersion   *string                `protobuf:"bytes,3,opt,name=target_version,json=targetVersion,proto3,oneof" json:"target_version,omitempty"`
	Progress        *uint32                `protobuf:"varint,4,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	Message         *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Error           *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Changes         []string               `protobuf:"bytes,7,rep,name=changes,proto3" json:"changes,omitempty"`
	Trigger         *string                `protobuf:"bytes,8,opt,name=trigger,proto3,oneof" json:"trigger,omitempty"`
	UpdatedAt       *uint64                `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	DownloadedBytes *uint64                `protobuf:"varint,10,opt,name=downloaded_bytes,json=downloadedBytes,proto3,oneof" json:"downloaded_bytes,omitempty"`
	TotalBytes      *uint64                `protobuf:"varint,11,opt,name=total_bytes,json=totalBytes,proto3,oneof" json:"total_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateInfo) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdateInfo) GetCurrentVersion() string {
	if x != nil && x.CurrentVersion != nil {
		return *x.CurrentVersion
	}
	return ""
}

func (x *UpdateInfo) GetTargetVersion() string {
	if x != nil && x.TargetVersion != nil {
		return *x.TargetVersion
	}
	return ""
}

func (x *UpdateInfo) GetProgress() uint32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *UpdateInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *UpdateInfo) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *UpdateInfo) GetChanges() []string {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *UpdateInfo) GetTrigger() string {
	if x != nil && x.Trigger != nil {
		return *x.Trigger
	}
	return ""
}

func (x *UpdateInfo) GetUpdatedAt() uint64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *UpdateInfo) GetDownloadedBytes() uint64 {
	if x != nil && x.DownloadedBytes != nil {
		return *x.DownloadedBytes
	}
	return 0
}

func (x *UpdateInfo) GetTotalBytes() uint64 {
	if x != nil && x.TotalBytes != nil {
		return *x.TotalBytes
	}
	return 0
}

// face -> brain
type FaceToBrain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*FaceToBrain_VoiceState
	//	*FaceToBrain_UpdateAction
	//	*FaceToBrain_GetBinanceSettings
	Cmd           isFaceToBrain_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceToBrain) Reset() {
	*x = FaceToBrain{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceToBrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceToBrain) ProtoMessage() {}

func (x *FaceToBrain) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceToBrain.ProtoReflect.Descriptor instead.
func (*FaceToBrain) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{11}
}

func (x *FaceToBrain) GetCmd() isFaceToBrain_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *FaceToBrain) GetVoiceState() StateToggle {
	if x != nil {
		if x, ok := x.Cmd.(*FaceToBrain_VoiceState); ok {
			return x.VoiceState
		}
	}
	return StateToggle_STATE_UNKNOWN
}

func (x *FaceToBrain) GetUpdateAction() *UpdateAction {
	if x != nil {
		if x, ok := x.Cmd.(*FaceToBrain_UpdateAction); ok {
			return x.UpdateAction
		}
	}
	return nil
}

func (x *FaceToBrain) GetGetBinanceSettings() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Cmd.(*FaceToBrain_GetBinanceSettings); ok {
			return x.GetBinanceSettings
		}
	}
	return nil
}

type isFaceToBrain_Cmd interface {
	isFaceToBrain_Cmd()
}

type FaceToBrain_VoiceState struct {
	VoiceState StateToggle `protobuf:"varint,1,opt,name=voice_state,json=voiceState,proto3,enum=hi.ninja.StateToggle,oneof"` // 音频播放开始/结束，brain 据此控制麦克风静音
}

type FaceToBrain_UpdateAction struct {
	UpdateAction *UpdateAction `protobuf:"bytes,2,opt,name=update_action,json=updateAction,proto3,oneof"` //更新动作
}

type FaceToBrain_GetBinanceSettings struct {
	// face 重启后内存缓存是空的，用它主动要一次（本文件里空请求一律用 Empty，见 show_qr_code）
	GetBinanceSettings *emptypb.Empty `protobuf:"bytes,3,opt,name=get_binance_settings,json=getBinanceSettings,proto3,oneof"`
}

func (*FaceToBrain_VoiceState) isFaceToBrain_Cmd() {}

func (*FaceToBrain_UpdateAction) isFaceToBrain_Cmd() {}

func (*FaceToBrain_GetBinanceSettings) isFaceToBrain_Cmd() {}

// 插件下载/安装进度。
//
// NATIVE 插件是**云端交叉编译好的 .so,机器人自己去取** —— 几百 KB 到几 MB,
// 机器人的网可能很差。没有进度的话,用户在市场点了"购买"之后,face 上什么都不会变,
// 直到某一刻插件突然出现;中间那段沉默里,用户只会以为没买成、然后再点一次。
//
// 字段有意与固件更新(UpdaterStatus)同形:state / progress / 已下/共多少字节。
// **face 那边不该为"插件"和"固件"学两套进度模型。**
type PluginProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  *string                `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Title *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"` // 给用户看的名字;取不到就退回 uuid
	State *PluginProgress_State  `protobuf:"varint,3,opt,name=state,proto3,enum=hi.ninja.PluginProgress_State,oneof" json:"state,omitempty"`
	// 0-100。**总长度未知时恒为 0** —— 服务端不给 Content-Length 是有可能的,
	// 那时候宁可不显示百分比,也别编一个会往回跳的数字。
	Progress        *uint32 `protobuf:"varint,4,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	DownloadedBytes *uint64 `protobuf:"varint,5,opt,name=downloaded_bytes,json=downloadedBytes,proto3,oneof" json:"downloaded_bytes,omitempty"`
	TotalBytes      *uint64 `protobuf:"varint,6,opt,name=total_bytes,json=totalBytes,proto3,oneof" json:"total_bytes,omitempty"` // 0 = 未知
	Message         *string `protobuf:"bytes,7,opt,name=message,proto3,oneof" json:"message,omitempty"`                          // 失败原因(state=FAILED 时)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginProgress) Reset() {
	*x = PluginProgress{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginProgress) ProtoMessage() {}

func (x *PluginProgress) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginProgress.ProtoReflect.Descriptor instead.
func (*PluginProgress) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{12}
}

func (x *PluginProgress) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *PluginProgress) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PluginProgress) GetState() PluginProgress_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return PluginProgress_STATE_UNKNOWN
}

func (x *PluginProgress) GetProgress() uint32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *PluginProgress) GetDownloadedBytes() uint64 {
	if x != nil && x.DownloadedBytes != nil {
		return *x.DownloadedBytes
	}
	return 0
}

func (x *PluginProgress) GetTotalBytes() uint64 {
	if x != nil && x.TotalBytes != nil {
		return *x.TotalBytes
	}
	return 0
}

func (x *PluginProgress) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// 更新动作
type UpdateAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *UpdateAction_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=hi.ninja.UpdateAction_Action,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAction) Reset() {
	*x = UpdateAction{}
	mi := &file_hi_ninja_ipc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction) ProtoMessage() {}

func (x *UpdateAction) ProtoReflect() protoreflect.Message {
	mi := &file_hi_ninja_ipc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction.ProtoReflect.Descriptor instead.
func (*UpdateAction) Descriptor() ([]byte, []int) {
	return file_hi_ninja_ipc_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAction) GetAction() UpdateAction_Action {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return UpdateAction_ACTION_UNKNOWN
}

var File_hi_ninja_ipc_proto protoreflect.FileDescriptor

const file_hi_ninja_ipc_proto_rawDesc = "" +
	"\n" +
	"\x12hi/ninja/ipc.proto\x12\bhi.ninja\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0fhi/common.proto\x1a\x13hi/club/group.proto\x1a\x17hi/club/messaging.proto\x1a\x12hi/ai/plugin.proto\x1a\x15hi/did/transfer.proto\"Q\n" +
	"\tRobotInit\x12 \n" +
	"\x05robot\x18\x01 \x01(\v2\n" +
	".hi.EntityR\x05robot\x12\"\n" +
	"\x06master\x18\x02 \x01(\v2\n" +
	".hi.EntityR\x06master\",\n" +
	"\n" +
	"FriendList\x12\x1e\n" +
	"\x04list\x18\x01 \x03(\v2\n" +
	".hi.EntityR\x04list\"7\n" +
	"\rGroupInfoList\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.hi.club.GroupInfoR\x04list\"\\\n" +
	"\vMasterEvent\x12\"\n" +
	"\x06master\x18\x01 \x01(\v2\n" +
	".hi.EntityR\x06master\x12\x1d\n" +
	"\atrigger\x18\x02 \x01(\tH\x00R\atrigger\x88\x01\x01B\n" +
	"\n" +
	"\b_trigger\"R\n" +
	"\tTextReply\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\tH\x00R\x04uuid\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x01R\x05value\x88\x01\x01B\a\n" +
	"\x05_uuidB\b\n" +
	"\x06_value\"R\n" +
	"\tAudioPlay\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\tH\x00R\x04uuid\x88\x01\x01\x12\x19\n" +
	"\x05audio\x18\x02 \x01(\fH\x01R\x05audio\x88\x01\x01B\a\n" +
	"\x05_uuidB\b\n" +
	"\x06_audio\"\x93\x01\n" +
	"\x0fBinanceSettings\x12>\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1c.hi.ninja.BinanceCredentialsR\vcredentials\x12,\n" +
	"\x0finitial_capital\x18\x02 \x01(\tH\x00R\x0einitialCapital\x88\x01\x01B\x12\n" +
	"\x10_initial_capital\"q\n" +
	"\x12BinanceCredentials\x12\x1c\n" +
	"\aapi_key\x18\x01 \x01(\tH\x00R\x06apiKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tH\x01R\tapiSecret\x88\x01\x01B\n" +
	"\n" +
	"\b_api_keyB\r\n" +
	"\v_api_secret\"\x93\n" +
	"\n" +
	"\vBrainToFace\x124\n" +
	"\n" +
	"init_robot\x18\x01 \x01(\v2\x13.hi.ninja.RobotInitH\x00R\tinitRobot\x128\n" +
	"\vshow_listen\x18\x02 \x01(\x0e2\x15.hi.ninja.StateToggleH\x00R\n" +
	"showListen\x126\n" +
	"\fshow_emotion\x18\x03 \x01(\x0e2\x11.hi.ninja.EmotionH\x00R\vshowEmotion\x12:\n" +
	"\x0fshow_im_request\x18\x04 \x01(\v2\x10.hi.club.MessageH\x00R\rshowImRequest\x129\n" +
	"\rshow_im_reply\x18\x05 \x01(\v2\x13.hi.ninja.TextReplyH\x00R\vshowImReply\x12?\n" +
	"\x10show_voice_reply\x18\x06 \x01(\v2\x13.hi.ninja.TextReplyH\x00R\x0eshowVoiceReply\x12:\n" +
	"\fshow_qr_code\x18\a \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"showQrCode\x12-\n" +
	"\vevent_robot\x18\b \x01(\v2\n" +
	".hi.EntityH\x00R\n" +
	"eventRobot\x12:\n" +
	"\fevent_master\x18\t \x01(\v2\x15.hi.ninja.MasterEventH\x00R\veventMaster\x129\n" +
	"\revent_members\x18\n" +
	" \x01(\v2\x12.hi.club.GroupInfoH\x00R\feventMembers\x126\n" +
	"\fevent_plugin\x18\v \x01(\v2\x11.hi.ai.PluginViewH\x00R\veventPlugin\x12N\n" +
	"\x15event_plugin_progress\x18\x14 \x01(\v2\x18.hi.ninja.PluginProgressH\x00R\x13eventPluginProgress\x12B\n" +
	"\x11event_transaction\x18\f \x01(\v2\x13.hi.did.TransactionH\x00R\x10eventTransaction\x124\n" +
	"\n" +
	"play_audio\x18\r \x01(\v2\x13.hi.ninja.AudioPlayH\x00R\tplayAudio\x12;\n" +
	"\revent_friends\x18\x0f \x01(\v2\x14.hi.ninja.FriendListH\x00R\feventFriends\x12<\n" +
	"\x13event_friend_delete\x18\x0e \x01(\v2\n" +
	".hi.EntityH\x00R\x11eventFriendDelete\x126\n" +
	"\x10event_friend_add\x18\x10 \x01(\v2\n" +
	".hi.EntityH\x00R\x0eeventFriendAdd\x12<\n" +
	"\fmembers_init\x18\x11 \x01(\v2\x17.hi.ninja.GroupInfoListH\x00R\vmembersInit\x12:\n" +
	"\fevent_status\x18\x12 \x01(\v2\x15.hi.ninja.StatusEventH\x00R\veventStatus\x129\n" +
	"\fevent_update\x18\x13 \x01(\v2\x14.hi.ninja.UpdateInfoH\x00R\veventUpdate\x12Q\n" +
	"\x16event_binance_settings\x18\x15 \x01(\v2\x19.hi.ninja.BinanceSettingsH\x00R\x14eventBinanceSettingsB\x05\n" +
	"\x03cmd\"m\n" +
	"\vStatusEvent\x12\x15\n" +
	"\x03ntp\x18\x01 \x01(\bH\x00R\x03ntp\x88\x01\x01\x12\x17\n" +
	"\x04wifi\x18\x02 \x01(\bH\x01R\x04wifi\x88\x01\x01\x12\x15\n" +
	"\x03usb\x18\x03 \x01(\bH\x02R\x03usb\x88\x01\x01B\x06\n" +
	"\x04_ntpB\a\n" +
	"\x05_wifiB\x06\n" +
	"\x04_usb\"\xa3\x04\n" +
	"\n" +
	"UpdateInfo\x12\x19\n" +
	"\x05state\x18\x01 \x01(\tH\x00R\x05state\x88\x01\x01\x12,\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tH\x01R\x0ecurrentVersion\x88\x01\x01\x12*\n" +
	"\x0etarget_version\x18\x03 \x01(\tH\x02R\rtargetVersion\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x04 \x01(\rH\x03R\bprogress\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x04R\amessage\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x05R\x05error\x88\x01\x01\x12\x18\n" +
	"\achanges\x18\a \x03(\tR\achanges\x12\x1d\n" +
	"\atrigger\x18\b \x01(\tH\x06R\atrigger\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\t \x01(\x04H\aR\tupdatedAt\x88\x01\x01\x12.\n" +
	"\x10downloaded_bytes\x18\n" +
	" \x01(\x04H\bR\x0fdownloadedBytes\x88\x01\x01\x12$\n" +
	"\vtotal_bytes\x18\v \x01(\x04H\tR\n" +
	"totalBytes\x88\x01\x01B\b\n" +
	"\x06_stateB\x12\n" +
	"\x10_current_versionB\x11\n" +
	"\x0f_target_versionB\v\n" +
	"\t_progressB\n" +
	"\n" +
	"\b_messageB\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_triggerB\r\n" +
	"\v_updated_atB\x13\n" +
	"\x11_downloaded_bytesB\x0e\n" +
	"\f_total_bytes\"\xd9\x01\n" +
	"\vFaceToBrain\x128\n" +
	"\vvoice_state\x18\x01 \x01(\x0e2\x15.hi.ninja.StateToggleH\x00R\n" +
	"voiceState\x12=\n" +
	"\rupdate_action\x18\x02 \x01(\v2\x16.hi.ninja.UpdateActionH\x00R\fupdateAction\x12J\n" +
	"\x14get_binance_settings\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x12getBinanceSettingsB\x05\n" +
	"\x03cmd\"\xdb\x03\n" +
	"\x0ePluginProgress\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\tH\x00R\x04uuid\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x01R\x05title\x88\x01\x01\x129\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.hi.ninja.PluginProgress.StateH\x02R\x05state\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x04 \x01(\rH\x03R\bprogress\x88\x01\x01\x12.\n" +
	"\x10downloaded_bytes\x18\x05 \x01(\x04H\x04R\x0fdownloadedBytes\x88\x01\x01\x12$\n" +
	"\vtotal_bytes\x18\x06 \x01(\x04H\x05R\n" +
	"totalBytes\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\a \x01(\tH\x06R\amessage\x88\x01\x01\"i\n" +
	"\x05State\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATE_DOWNLOADING\x10\x01\x12\x14\n" +
	"\x10STATE_INSTALLING\x10\x02\x12\x0e\n" +
	"\n" +
	"STATE_DONE\x10\x03\x12\x10\n" +
	"\fSTATE_FAILED\x10\x04B\a\n" +
	"\x05_uuidB\b\n" +
	"\x06_titleB\b\n" +
	"\x06_stateB\v\n" +
	"\t_progressB\x13\n" +
	"\x11_downloaded_bytesB\x0e\n" +
	"\f_total_bytesB\n" +
	"\n" +
	"\b_message\"\xab\x01\n" +
	"\fUpdateAction\x12:\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1d.hi.ninja.UpdateAction.ActionH\x00R\x06action\x88\x01\x01\"T\n" +
	"\x06Action\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fACTION_CHECK\x10\x01\x12\x10\n" +
	"\fACTION_APPLY\x10\x02\x12\x12\n" +
	"\x0eACTION_DISMISS\x10\x03B\t\n" +
	"\a_action*@\n" +
	"\vStateToggle\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSTATE_START\x10\x01\x12\r\n" +
	"\tSTATE_END\x10\x02*[\n" +
	"\aEmotion\x12\x13\n" +
	"\x0fEMOTION_UNKNOWN\x10\x00\x12\x11\n" +
	"\rEMOTION_ANGER\x10\x01\x12\x11\n" +
	"\rEMOTION_LAUGH\x10\x02\x12\x15\n" +
	"\x11EMOTION_FRUSTRATE\x10\x03B\x85\x01\n" +
	"\fcom.hi.ninjaB\bIpcProtoP\x01Z*github.com/HiWorld-56/hi-proto/go/hi/ninja\xa2\x02\x03HNX\xaa\x02\bHi.Ninja\xca\x02\bHi\\Ninja\xe2\x02\x14Hi\\Ninja\\GPBMetadata\xea\x02\tHi::Ninjab\x06proto3"

var (
	file_hi_ninja_ipc_proto_rawDescOnce sync.Once
	file_hi_ninja_ipc_proto_rawDescData []byte
)

func file_hi_ninja_ipc_proto_rawDescGZIP() []byte {
	file_hi_ninja_ipc_proto_rawDescOnce.Do(func() {
		file_hi_ninja_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hi_ninja_ipc_proto_rawDesc), len(file_hi_ninja_ipc_proto_rawDesc)))
	})
	return file_hi_ninja_ipc_proto_rawDescData
}

var file_hi_ninja_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_hi_ninja_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_hi_ninja_ipc_proto_goTypes = []any{
	(StateToggle)(0),           // 0: hi.ninja.StateToggle
	(Emotion)(0),               // 1: hi.ninja.Emotion
	(PluginProgress_State)(0),  // 2: hi.ninja.PluginProgress.State
	(UpdateAction_Action)(0),   // 3: hi.ninja.UpdateAction.Action
	(*RobotInit)(nil),          // 4: hi.ninja.RobotInit
	(*FriendList)(nil),         // 5: hi.ninja.FriendList
	(*GroupInfoList)(nil),      // 6: hi.ninja.GroupInfoList
	(*MasterEvent)(nil),        // 7: hi.ninja.MasterEvent
	(*TextReply)(nil),          // 8: hi.ninja.TextReply
	(*AudioPlay)(nil),          // 9: hi.ninja.AudioPlay
	(*BinanceSettings)(nil),    // 10: hi.ninja.BinanceSettings
	(*BinanceCredentials)(nil), // 11: hi.ninja.BinanceCredentials
	(*BrainToFace)(nil),        // 12: hi.ninja.BrainToFace
	(*StatusEvent)(nil),        // 13: hi.ninja.StatusEvent
	(*UpdateInfo)(nil),         // 14: hi.ninja.UpdateInfo
	(*FaceToBrain)(nil),        // 15: hi.ninja.FaceToBrain
	(*PluginProgress)(nil),     // 16: hi.ninja.PluginProgress
	(*UpdateAction)(nil),       // 17: hi.ninja.UpdateAction
	(*hi.Entity)(nil),          // 18: hi.Entity
	(*club.GroupInfo)(nil),     // 19: hi.club.GroupInfo
	(*club.Message)(nil),       // 20: hi.club.Message
	(*emptypb.Empty)(nil),      // 21: google.protobuf.Empty
	(*ai.PluginView)(nil),      // 22: hi.ai.PluginView
	(*did.Transaction)(nil),    // 23: hi.did.Transaction
}
var file_hi_ninja_ipc_proto_depIdxs = []int32{
	18, // 0: hi.ninja.RobotInit.robot:type_name -> hi.Entity
	18, // 1: hi.ninja.RobotInit.master:type_name -> hi.Entity
	18, // 2: hi.ninja.FriendList.list:type_name -> hi.Entity
	19, // 3: hi.ninja.GroupInfoList.list:type_name -> hi.club.GroupInfo
	18, // 4: hi.ninja.MasterEvent.master:type_name -> hi.Entity
	11, // 5: hi.ninja.BinanceSettings.credentials:type_name -> hi.ninja.BinanceCredentials
	4,  // 6: hi.ninja.BrainToFace.init_robot:type_name -> hi.ninja.RobotInit
	0,  // 7: hi.ninja.BrainToFace.show_listen:type_name -> hi.ninja.StateToggle
	1,  // 8: hi.ninja.BrainToFace.show_emotion:type_name -> hi.ninja.Emotion
	20, // 9: hi.ninja.BrainToFace.show_im_request:type_name -> hi.club.Message
	8,  // 10: hi.ninja.BrainToFace.show_im_reply:type_name -> hi.ninja.TextReply
	8,  // 11: hi.ninja.BrainToFace.show_voice_reply:type_name -> hi.ninja.TextReply
	21, // 12: hi.ninja.BrainToFace.show_qr_code:type_name -> google.protobuf.Empty
	18, // 13: hi.ninja.BrainToFace.event_robot:type_name -> hi.Entity
	7,  // 14: hi.ninja.BrainToFace.event_master:type_name -> hi.ninja.MasterEvent
	19, // 15: hi.ninja.BrainToFace.event_members:type_name -> hi.club.GroupInfo
	22, // 16: hi.ninja.BrainToFace.event_plugin:type_name -> hi.ai.PluginView
	16, // 17: hi.ninja.BrainToFace.event_plugin_progress:type_name -> hi.ninja.PluginProgress
	23, // 18: hi.ninja.BrainToFace.event_transaction:type_name -> hi.did.Transaction
	9,  // 19: hi.ninja.BrainToFace.play_audio:type_name -> hi.ninja.AudioPlay
	5,  // 20: hi.ninja.BrainToFace.event_friends:type_name -> hi.ninja.FriendList
	18, // 21: hi.ninja.BrainToFace.event_friend_delete:type_name -> hi.Entity
	18, // 22: hi.ninja.BrainToFace.event_friend_add:type_name -> hi.Entity
	6,  // 23: hi.ninja.BrainToFace.members_init:type_name -> hi.ninja.GroupInfoList
	13, // 24: hi.ninja.BrainToFace.event_status:type_name -> hi.ninja.StatusEvent
	14, // 25: hi.ninja.BrainToFace.event_update:type_name -> hi.ninja.UpdateInfo
	10, // 26: hi.ninja.BrainToFace.event_binance_settings:type_name -> hi.ninja.BinanceSettings
	0,  // 27: hi.ninja.FaceToBrain.voice_state:type_name -> hi.ninja.StateToggle
	17, // 28: hi.ninja.FaceToBrain.update_action:type_name -> hi.ninja.UpdateAction
	21, // 29: hi.ninja.FaceToBrain.get_binance_settings:type_name -> google.protobuf.Empty
	2,  // 30: hi.ninja.PluginProgress.state:type_name -> hi.ninja.PluginProgress.State
	3,  // 31: hi.ninja.UpdateAction.action:type_name -> hi.ninja.UpdateAction.Action
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_hi_ninja_ipc_proto_init() }
func file_hi_ninja_ipc_proto_init() {
	if File_hi_ninja_ipc_proto != nil {
		return
	}
	file_hi_ninja_ipc_proto_msgTypes[3].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[4].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[5].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[6].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[7].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[8].OneofWrappers = []any{
		(*BrainToFace_InitRobot)(nil),
		(*BrainToFace_ShowListen)(nil),
		(*BrainToFace_ShowEmotion)(nil),
		(*BrainToFace_ShowImRequest)(nil),
		(*BrainToFace_ShowImReply)(nil),
		(*BrainToFace_ShowVoiceReply)(nil),
		(*BrainToFace_ShowQrCode)(nil),
		(*BrainToFace_EventRobot)(nil),
		(*BrainToFace_EventMaster)(nil),
		(*BrainToFace_EventMembers)(nil),
		(*BrainToFace_EventPlugin)(nil),
		(*BrainToFace_EventPluginProgress)(nil),
		(*BrainToFace_EventTransaction)(nil),
		(*BrainToFace_PlayAudio)(nil),
		(*BrainToFace_EventFriends)(nil),
		(*BrainToFace_EventFriendDelete)(nil),
		(*BrainToFace_EventFriendAdd)(nil),
		(*BrainToFace_MembersInit)(nil),
		(*BrainToFace_EventStatus)(nil),
		(*BrainToFace_EventUpdate)(nil),
		(*BrainToFace_EventBinanceSettings)(nil),
	}
	file_hi_ninja_ipc_proto_msgTypes[9].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[10].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[11].OneofWrappers = []any{
		(*FaceToBrain_VoiceState)(nil),
		(*FaceToBrain_UpdateAction)(nil),
		(*FaceToBrain_GetBinanceSettings)(nil),
	}
	file_hi_ninja_ipc_proto_msgTypes[12].OneofWrappers = []any{}
	file_hi_ninja_ipc_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hi_ninja_ipc_proto_rawDesc), len(file_hi_ninja_ipc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hi_ninja_ipc_proto_goTypes,
		DependencyIndexes: file_hi_ninja_ipc_proto_depIdxs,
		EnumInfos:         file_hi_ninja_ipc_proto_enumTypes,
		MessageInfos:      file_hi_ninja_ipc_proto_msgTypes,
	}.Build()
	File_hi_ninja_ipc_proto = out.File
	file_hi_ninja_ipc_proto_goTypes = nil
	file_hi_ninja_ipc_proto_depIdxs = nil
}
