// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hi/club/source.proto

package club

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	hi "github.com/HiWorld-56/hi-proto/go/hi"
	ai "github.com/HiWorld-56/hi-proto/go/hi/ai"
	source "github.com/HiWorld-56/hi-proto/go/hi/source"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadResourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResourceReq) Reset() {
	*x = DownloadResourceReq{}
	mi := &file_hi_club_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResourceReq) ProtoMessage() {}

func (x *DownloadResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_hi_club_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResourceReq.ProtoReflect.Descriptor instead.
func (*DownloadResourceReq) Descriptor() ([]byte, []int) {
	return file_hi_club_source_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadResourceReq) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type DownloadResourceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResourceResp) Reset() {
	*x = DownloadResourceResp{}
	mi := &file_hi_club_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResourceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResourceResp) ProtoMessage() {}

func (x *DownloadResourceResp) ProtoReflect() protoreflect.Message {
	mi := &file_hi_club_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResourceResp.ProtoReflect.Descriptor instead.
func (*DownloadResourceResp) Descriptor() ([]byte, []int) {
	return file_hi_club_source_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadResourceResp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_hi_club_source_proto protoreflect.FileDescriptor

const file_hi_club_source_proto_rawDesc = "" +
	"\n" +
	"\x14hi/club/source.proto\x12\ahi.club\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12hi/ai/plugin.proto\x1a\x14hi/ai/training.proto\x1a\x1bbuf/validate/validate.proto\x1a\x0fhi/common.proto\x1a\x16hi/source/source.proto\x1a\x10hi/options.proto\"E\n" +
	"\x13DownloadResourceReq\x12&\n" +
	"\x03url\x18\x01 \x01(\tB\x0f\xbaH\f\xc8\x01\x01r\a2\x05^\\S+$H\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"M\n" +
	"\x14DownloadResourceResp\x12#\n" +
	"\acontent\x18\x01 \x01(\fB\x04\x90\xb5\x18\x01H\x00R\acontent\x88\x01\x01:\x04\x98\xb5\x18\x01B\n" +
	"\n" +
	"\b_content2\x97\b\n" +
	"\x06Source\x124\n" +
	"\fUploadAvatar\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x129\n" +
	"\x11UploadGroupAvatar\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x12=\n" +
	"\x15UploadGroupBackground\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x12N\n" +
	"\bDownload\x12\x1c.hi.club.DownloadResourceReq\x1a\x1d.hi.club.DownloadResourceResp\"\x05\x8a\xb5\x18\x01\x02\x12V\n" +
	"\x0eDownloadStream\x12\x1c.hi.source.DownloadStreamReq\x1a\x1d.hi.source.DownloadStreamResp\"\x05\x8a\xb5\x18\x01\x020\x01\x122\n" +
	"\n" +
	"UploadTemp\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x12@\n" +
	"\x10UploadTempStream\x12\x13.hi.UploadStreamReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02(\x01\x121\n" +
	"\tUploadLog\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x124\n" +
	"\fUploadScript\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x12B\n" +
	"\x12UploadScriptStream\x12\x13.hi.UploadStreamReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02(\x01\x12L\n" +
	"\x0eDownloadScript\x12\x18.hi.ai.DownloadScriptReq\x1a\x19.hi.ai.DownloadScriptResp\"\x05\x8a\xb5\x18\x01\x02\x12I\n" +
	"\x12UploadTrainingFile\x12\x14.hi.ai.UploadFileReq\x1a\x16.google.protobuf.Empty\"\x05\x8a\xb5\x18\x01\x02\x12N\n" +
	"\x14DownloadTrainingFile\x12\x16.hi.ai.DownloadFileReq\x1a\x17.hi.ai.DownloadFileResp\"\x05\x8a\xb5\x18\x01\x02\x122\n" +
	"\n" +
	"UploadLogo\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x125\n" +
	"\rUploadSummary\x12\r.hi.UploadReq\x1a\x0e.hi.UploadResp\"\x05\x8a\xb5\x18\x01\x02\x12>\n" +
	"\x06Delete\x12\x15.hi.DeleteResourceReq\x1a\x16.google.protobuf.Empty\"\x05\x8a\xb5\x18\x01\x02B\x82\x01\n" +
	"\vcom.hi.clubB\vSourceProtoP\x01Z)github.com/HiWorld-56/hi-proto/go/hi/club\xa2\x02\x03HCX\xaa\x02\aHi.Club\xca\x02\aHi\\Club\xe2\x02\x13Hi\\Club\\GPBMetadata\xea\x02\bHi::Clubb\x06proto3"

var (
	file_hi_club_source_proto_rawDescOnce sync.Once
	file_hi_club_source_proto_rawDescData []byte
)

func file_hi_club_source_proto_rawDescGZIP() []byte {
	file_hi_club_source_proto_rawDescOnce.Do(func() {
		file_hi_club_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hi_club_source_proto_rawDesc), len(file_hi_club_source_proto_rawDesc)))
	})
	return file_hi_club_source_proto_rawDescData
}

var file_hi_club_source_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hi_club_source_proto_goTypes = []any{
	(*DownloadResourceReq)(nil),       // 0: hi.club.DownloadResourceReq
	(*DownloadResourceResp)(nil),      // 1: hi.club.DownloadResourceResp
	(*hi.UploadReq)(nil),              // 2: hi.UploadReq
	(*source.DownloadStreamReq)(nil),  // 3: hi.source.DownloadStreamReq
	(*hi.UploadStreamReq)(nil),        // 4: hi.UploadStreamReq
	(*ai.DownloadScriptReq)(nil),      // 5: hi.ai.DownloadScriptReq
	(*ai.UploadFileReq)(nil),          // 6: hi.ai.UploadFileReq
	(*ai.DownloadFileReq)(nil),        // 7: hi.ai.DownloadFileReq
	(*hi.DeleteResourceReq)(nil),      // 8: hi.DeleteResourceReq
	(*hi.UploadResp)(nil),             // 9: hi.UploadResp
	(*source.DownloadStreamResp)(nil), // 10: hi.source.DownloadStreamResp
	(*ai.DownloadScriptResp)(nil),     // 11: hi.ai.DownloadScriptResp
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
	(*ai.DownloadFileResp)(nil),       // 13: hi.ai.DownloadFileResp
}
var file_hi_club_source_proto_depIdxs = []int32{
	2,  // 0: hi.club.Source.UploadAvatar:input_type -> hi.UploadReq
	2,  // 1: hi.club.Source.UploadGroupAvatar:input_type -> hi.UploadReq
	2,  // 2: hi.club.Source.UploadGroupBackground:input_type -> hi.UploadReq
	0,  // 3: hi.club.Source.Download:input_type -> hi.club.DownloadResourceReq
	3,  // 4: hi.club.Source.DownloadStream:input_type -> hi.source.DownloadStreamReq
	2,  // 5: hi.club.Source.UploadTemp:input_type -> hi.UploadReq
	4,  // 6: hi.club.Source.UploadTempStream:input_type -> hi.UploadStreamReq
	2,  // 7: hi.club.Source.UploadLog:input_type -> hi.UploadReq
	2,  // 8: hi.club.Source.UploadScript:input_type -> hi.UploadReq
	4,  // 9: hi.club.Source.UploadScriptStream:input_type -> hi.UploadStreamReq
	5,  // 10: hi.club.Source.DownloadScript:input_type -> hi.ai.DownloadScriptReq
	6,  // 11: hi.club.Source.UploadTrainingFile:input_type -> hi.ai.UploadFileReq
	7,  // 12: hi.club.Source.DownloadTrainingFile:input_type -> hi.ai.DownloadFileReq
	2,  // 13: hi.club.Source.UploadLogo:input_type -> hi.UploadReq
	2,  // 14: hi.club.Source.UploadSummary:input_type -> hi.UploadReq
	8,  // 15: hi.club.Source.Delete:input_type -> hi.DeleteResourceReq
	9,  // 16: hi.club.Source.UploadAvatar:output_type -> hi.UploadResp
	9,  // 17: hi.club.Source.UploadGroupAvatar:output_type -> hi.UploadResp
	9,  // 18: hi.club.Source.UploadGroupBackground:output_type -> hi.UploadResp
	1,  // 19: hi.club.Source.Download:output_type -> hi.club.DownloadResourceResp
	10, // 20: hi.club.Source.DownloadStream:output_type -> hi.source.DownloadStreamResp
	9,  // 21: hi.club.Source.UploadTemp:output_type -> hi.UploadResp
	9,  // 22: hi.club.Source.UploadTempStream:output_type -> hi.UploadResp
	9,  // 23: hi.club.Source.UploadLog:output_type -> hi.UploadResp
	9,  // 24: hi.club.Source.UploadScript:output_type -> hi.UploadResp
	9,  // 25: hi.club.Source.UploadScriptStream:output_type -> hi.UploadResp
	11, // 26: hi.club.Source.DownloadScript:output_type -> hi.ai.DownloadScriptResp
	12, // 27: hi.club.Source.UploadTrainingFile:output_type -> google.protobuf.Empty
	13, // 28: hi.club.Source.DownloadTrainingFile:output_type -> hi.ai.DownloadFileResp
	9,  // 29: hi.club.Source.UploadLogo:output_type -> hi.UploadResp
	9,  // 30: hi.club.Source.UploadSummary:output_type -> hi.UploadResp
	12, // 31: hi.club.Source.Delete:output_type -> google.protobuf.Empty
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hi_club_source_proto_init() }
func file_hi_club_source_proto_init() {
	if File_hi_club_source_proto != nil {
		return
	}
	file_hi_club_source_proto_msgTypes[0].OneofWrappers = []any{}
	file_hi_club_source_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hi_club_source_proto_rawDesc), len(file_hi_club_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hi_club_source_proto_goTypes,
		DependencyIndexes: file_hi_club_source_proto_depIdxs,
		MessageInfos:      file_hi_club_source_proto_msgTypes,
	}.Build()
	File_hi_club_source_proto = out.File
	file_hi_club_source_proto_goTypes = nil
	file_hi_club_source_proto_depIdxs = nil
}
